Assignment/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tracker.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    #path('accounts/signup/student/', views.StudentSignUpView.as_view(), name='student_signup'),
    #path('accounts/signup/teacher/', views.TeacherSignUpView.as_view(), name='teacher_signup'),

]

tracker/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import TemplateView

app_name = 'tracker'

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/signup/student/', views.StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/', views.TeacherSignUpView.as_view(), name='teacher_signup'),
    path('assignmentlist/', views.assignmentlist, name = 'assignmentlist'),
    path('tasklist/', views.tasklist, name='tasklist'),
    #path('tasklist/', views.TaskListView.as_view(), name='tasklist'),
    path('interests/', views.StudentInterestsView.as_view(), name='student_interests'),
    path('assignment/add/', views.AssignmentCreateView.as_view(), name='assignment_add'),
    path('upload/<int:pk>',views.upload,name='upload'),
    path('solutionupload/<int:pk>',views.solutionupload,name='solutionupload'),
    path('grade/', views.grade, name='grade'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tracker/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import AbstractUser
from django.utils.html import escape, mark_safe


# Create your models here.
class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)

class Grade(models.Model):
    name = models.CharField(max_length=30)
    color = models.CharField(max_length=7, default='#007bff')

    def __str__(self):
        return self.name

    def get_html_badge(self):
        name = escape(self.name)
        color = escape(self.color)
        html = '<span class="badge badge-primary" style="background-color: %s">%s</span>' % (color, name)
        return mark_safe(html)

class Assignment(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE,related_name='assigns')
    title = models.CharField(max_length=255)
    grade = models.ForeignKey(Grade, on_delete=models.CASCADE, related_name='assigns')
    filename = models.CharField(max_length=255)
    duedate   = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return  self.title


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    assignments = models.ManyToManyField(Assignment)
    interests = models.ManyToManyField(Grade, related_name='interested_students')

    def __str__(self):
        return self.user.username

tracker/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.forms.utils import ValidationError

from .models import  User , Student ,Grade ,Assignment


class TeacherSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_teacher = True
        if commit:
            user.save()
        return user


class StudentSignUpForm(UserCreationForm):
    interests = forms.ModelMultipleChoiceField(
        queryset=Grade.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )

    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_student = True
        user.save()
        student = Student.objects.create(user=user)
        student.interests.add(*self.cleaned_data.get('interests'))
        return user


class StudentInterestsForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('interests', )
        widgets = {
            'interests': forms.CheckboxSelectMultiple
        }


class AssignmentForm(forms.ModelForm):
    class Meta:
        model = Assignment
        fields = ('title', 'grade','filename',)

'''
class DocumentForm(forms.ModelForm):
    class Meta:
        model = Assignment
        fields = ('filename', 'document', )
'''

tracker/views.py
import os

from django.conf import settings
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth import login
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView
from .models import User, Assignment, Student
from .forms import StudentSignUpForm, TeacherSignUpForm, StudentInterestsForm, AssignmentForm
from django.contrib import messages
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse, request, HttpResponseRedirect, Http404
from django.utils import timezone



def home(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return redirect('tracker:assignmentlist')
        else:
            #return redirect('tracker:tasklist')
            return redirect('tracker:grade')
    return render(request, 'tracker/home.html')

class TeacherSignUpView(CreateView):
    model = User
    form_class = TeacherSignUpForm
    template_name = 'tracker/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'teacher'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('tracker:assignmentlist')


class StudentSignUpView(CreateView):
    model = User
    form_class = StudentSignUpForm
    template_name = 'tracker/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        print(user)
        login(self.request, user)
        return redirect('tracker:tasklist')


class StudentInterestsView(UpdateView):
    model = Student
    form_class = StudentInterestsForm
    template_name = 'tracker/interests_form.html'
    success_url = reverse_lazy('tracker:tasklist')

    def get_object(self):
        return self.request.user.student

    def form_valid(self, form):
        messages.success(self.request, 'Interests updated with success!')
        return super().form_valid(form)

class AssignmentCreateView(CreateView):
    model = Assignment
    fields = ('title', 'grade', 'filename','duedate',)
    template_name = 'tracker/assigment_add_form.html'

    def form_valid(self, form):
        assignment = form.save(commit=False)
        assignment.owner = self.request.user
        assignment.save()
        #request.session['title'] = assignment
        messages.success(self.request, 'The assignment was created with success!.')
        #return redirect('tracker:assignmentlist')
        return redirect('tracker:upload' ,pk=assignment.pk)

def assignmentlist(request):
    assignments = list(Assignment.objects.filter(owner=request.user))
    context = {'assignments':assignments}
    return render(request,'tracker/assignment_list.html',context)

def grade(request):
    #return  HttpResponse("here")
    return render(request,'tracker/grade.html')

def tasklist(request):
    if request.method == 'POST':
        grade = request.POST['grade']
        assignments = list(Assignment.objects.filter(grade=grade))
        submission_date  = timezone.now()
        context = {'assignments':assignments,'submission_date':submission_date}
        return render(request,'tracker/task_list.html',context)
    else:
        #return  HttpResponse("else")
        return render(request,'tracker/grade.html')

def upload(request,pk):
    if request.method == 'POST':
        print(request.method)
        uploaded_file = request.FILES['document']
        print(uploaded_file.name)
        print(uploaded_file.size)
        fs = FileSystemStorage()
        fs.save(uploaded_file.name,uploaded_file)
        Assignment.objects.filter(pk=pk).update(filename=uploaded_file.name)
        return redirect('tracker:assignmentlist')
    else:
        print(request.method)
    return render(request,'tracker/upload.html')


def solutionupload(request,pk):
    if request.method == 'POST':
        print(request.method)
        uploaded_file = request.FILES['document']
        print(uploaded_file.name)
        print(uploaded_file.size)
        fs = FileSystemStorage()
        fs.save(uploaded_file.name,uploaded_file)
        return redirect('tracker:tasklist')
    else:
        print(request.method)
    return render(request,'tracker/solutionupload.html')

tracker/templates/Tracker/_header.html
<h2>Assignments</h2>
<p class="text-muted">
  Subjects:{% for subject in user.student.interests.all %} {{ subject.get_html_badge }}{% endfor %}
  <a href="{% url 'tracker:student_interests' %}"><small>(update interests)</small></a>
</p>

tracker/templates/Tracker/assigment_add_form.html
{% extends 'tracker/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'tracker:assignmentlist' %}">My Assignments</a></li>
      <li class="breadcrumb-item active" aria-current="page">Add a new assignment</li>
    </ol>
  </nav>
  <h2 class="mb-3">Add a new assignment</h2>
  <div class="row">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save</button>
        <a href=# class="btn btn-outline-secondary" role="button">Nevermind</a>
      </form>
      <p></p>
    </div>
  </div>

{% endblock %}

tracker/templates/Tracker/assignment_list.html
{% extends 'tracker/base.html' %}
{% block content %}

  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">My Assigments</li>
    </ol>
  </nav>
  <h2 class="mb-3">My Assignments</h2>
   <a href="{% url 'tracker:assignment_add' %}" class="btn btn-primary mb-3" role="button">Add Assignment</a>
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Title</th>
          <th>File</th>
          <th>Due Date</th>
          <th>File Path </th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for assignment in assignments %}
          <tr>
            <td class="align-middle">{{ assignment.title }}</td>
            <td class="align-middle">{{ assignment.filename }}</td>
            <td class="align-middle">{{ assignment.duedate }}</td>
            <td class="align-middle"><a style="color: #8C001A" href="/media/{{ assignment.filename }}">/media/{{ assignment.filename }}</td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="5">You haven't created any assignment yet.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

tracker/templates/Tracker/base copy.html
{% load static %}
{% load crispy_forms_tags %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Assignment Tracker{% endblock %}</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <link href="https://fonts.googleapis.com/css?family=Clicker+Script" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/fontello-2f186091/css/fontello.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
    {% if user.is_authenticated and user.is_teacher %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/teachers.css' %}">
    {% else %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/students.css' %}">
    {% endif %}
  </head>
  <body>
    <a href="https://github.com/sibtc/django-multiple-user-types-example">
    <div class="container my-4">
      <div class="row justify-content-center">
        <div class="col-md-10 col-sm-12">
          <div class="row">
            <div class="col-6">
              <h1 class="logo">
                <a href=#>
                  Assignment Tracker
                  {% if user.is_authenticated %}
                    {% if user.is_teacher %}
                      <span class="icon-feather" data-toggle="tooltip" data-placement="right" title="Teacher profile"></span>
                    {% else %}
                      <span class="icon-graduation-cap" data-toggle="tooltip" data-placement="right" title="Student profile"></span>
                    {% endif %}
                  {% endif %}
                </a>
              </h1>
            </div>
            <div class="col-6 text-right">
              {% if user.is_authenticated %}
                <p class="pt-3">Logged in as <strong>{{ user.username }}</strong>. <a href="{% url 'accounts:logout' %}">Log out</a>.</p>
               {% else %}
                <a href="{% url 'accounts:login' %}" class="btn btn-light" role="button">Log in</a>
                <a href="{% url 'accounts:signup' %}" class="btn btn-primary" role="button">Sign up</a>
              {% endif %}
            </div>
          </div>
          <div class="card mb-3">
            <div class="card-body">
              {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endfor %}
              {% block content %}
              {% endblock %}
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript">
      $(function () {
        $('[data-toggle="tooltip"]').tooltip();
      })
    </script>
  </body>
</html>

tracker/templates/Tracker/base.html
{% load static %}
{% load crispy_forms_tags %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Assignment Tracker{% endblock %}</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <link href="https://fonts.googleapis.com/css?family=Clicker+Script" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/fontello-2f186091/css/fontello.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
  </head>
  <body>
    <div class="container my-4">
      <div class="row justify-content-center">
        <div class="col-md-10 col-sm-12">
          <div class="row">
            <div class="col-6">
              <h1 class="logo">
                <a href=#>
                  Assignment Tracker
                </a>
              </h1>
            </div>
            <div class="col-6 text-right">
              {% if user.is_authenticated %}
                <p class="pt-3">Logged in as <strong>{{ user.username }}</strong>.
                  <form class ="logout-link" action = "{% url 'accounts:logout' %}" method = "post">
                    {% csrf_token%}
                   <button type="submit">Logout</button>
                   </form>
                </li>

               {% else %}
                <a href="{% url 'accounts:login' %}" class="btn btn-light" role="button">Log in</a>
                <a href="{% url 'accounts:signup' %}" class="btn btn-primary" role="button">Sign up</a>
              {% endif %}
            </div>
          </div>
          <div class="card mb-3">
            <div class="card-body">
              {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endfor %}
              {% block content %}
              {% endblock %}
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript">
      $(function () {
        $('[data-toggle="tooltip"]').tooltip();
      })
    </script>
  </body>
</html>

tracker/templates/Tracker/grade.html
{% extends 'tracker/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

  <h2 class="mb-3">Enter your grade to continue ...</h2>
  <div class="row">
    <div class="col-md-6 col-sm-8 col-12">
      <form id="form" name="form" method="Post" action="/tasklist/">{%  csrf_token %}
        {% csrf_token %}
        {{ form|crispy }}
        <select name="grade" id="grade" class="form-control" style="color:#000000" >
          <option value="1" >Grade1</option>
          <option value="2" >Grade2</option>
          <option value="3" >Grade3</option>
          <option value="4" >Grade4</option>
          <option value="5" >Grade5</option>
        </select>
        <p></p>
        <input type="submit" value="Submit">
      </form>
      <p></p>
    </div>
  </div>

{% endblock %}

tracker/templates/Tracker/home.html
{% extends 'Tracker/base.html' %}

{% block content %}
  <h2>Welcome to the Assignment Tracker! <span class="icon-emo-happy"></span></h2>
  <p class="lead">
    If you already have an account, go ahead and <a href="{% url 'accounts:login' %}">log in</a>.
    <p></p>If you are new to Assignment Tracker, get started
    by creating a <a href="{% url 'tracker:student_signup' %}">student account</a> or a <a href="{% url 'tracker:teacher_signup' %}">teacher account</a>.
  </p>
  <hr>
  <h3>What's this about?</h3>
  <p>
    In this application, users can sign up as a student or a teacher. Teachers can add assignments and students submit their work.
  </p>
{% endblock %}

tracker/templates/Tracker/interests_form.html
{% extends 'tracker/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h2 class="mb-3">Update your interests</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Save changes</button>
    <a href="{% url 'tracker:tasklist' %}" class="btn btn-outline-secondary">Nevermind</a>
  </form>
{% endblock %}

tracker/templates/Tracker/signup_form.html
{% extends 'tracker/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
    <div class="col-md-8 col-sm-10 col-12">
      <h2>Sign up as a {{ user_type }}</h2>
      <form method="post" novalidate>
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Sign up</button>
      </form>
    </div>
  </div>
{% endblock %}

tracker/templates/Tracker/solutionupload.html
{% extends 'tracker/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">Please upload   as  <i> "StudentName_AssignmentTitle" e.g "abc_Grade1_math" </i> </li>
    </ol>
  </nav>
  <h2 class="mb-3">Add a new assignment</h2>
  <div class="row">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="file" name="document">
        <button type="submit" class="btn btn-success">Upload</button>
      </form>
      <p></p>
    </div>
  </div>

{% endblock %}

tracker/templates/Tracker/task_list.html
{% extends 'tracker/base.html' %}
{{assignments}}
{% block content %}
 <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">My Assigments</li>
    </ol>
  </nav>
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Title</th>
          <th>Assignment </th>
          <th>Due Date</th>
          <th>Submission Date</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for assignment in assignments %}
          <tr>
            <td class="align-middle">{{ assignment.title }}</td>
            <td class="align-middle"><a style="color: #8C001A" href="/media/{{ assignment.filename }}">/media/{{ assignment.filename }}</td>
            <td class="align-middle">{{ assignment.duedate}}</td>
            <td class="align-middle">{{ submission_date}}</td>
            <td class="align-middle"><a href="{% url 'tracker:solutionupload' pk=assignment.pk %}" class="btn btn-primary mb-3" role="button">Submit Solution</a></td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="4">No Assignments yet right now.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <p></p>

  </div>
{% endblock %}

tracker/templates/Tracker/upload.html
{% extends 'tracker/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'tracker:assignmentlist' %}">My Assignments</a></li>
      <li class="breadcrumb-item active" aria-current="page">Upload the asssigment questionaire</li>
    </ol>
  </nav>
  <h2 class="mb-3">Add a new assignment</h2>
  <div class="row">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="file" name="document">
        <button type="submit" class="btn btn-success">Upload</button>
      </form>
      <p></p>
    </div>
  </div>

{% endblock %}